import fs from 'node:fs';

import type { GeneratedScene, SceneDefaults } from './types.ts';

export class ScenesModuleEmitter {
	constructor(
		private readonly modulePrefix: string,
		private readonly sceneDefaults: SceneDefaults,
	) {}

	renderModule(scenes: GeneratedScene[]): string {
		const header = [
			'/**',
			' * AUTO-GENERATED by scripts/import-dd2vtt.ts',
			' *',
			' * Scenes imported from Dungeondraft Universal VTT (.dd2vtt) exports.',
			' * Edit the source .dd2vtt files and re-run the importer instead of',
			' * hand-editing this file.',
			' */',
			'',
			"import type { HarbingerScene } from './types';",
			'',
			'export const IMPORTED_DD2VTT_SCENES: HarbingerScene[] = [',
		].join('\n');

		const body = scenes.map((scene) => this.renderScene(scene)).join('\n');
		const footer = '\n];\n';
		return `${header}\n${body}${footer}`;
	}

	writeModule(outputPath: string, source: string): void {
		fs.writeFileSync(outputPath, source);
	}

	private renderScene(generated: GeneratedScene): string {
		const {
			spec,
			width,
			height,
			gridSize,
			walls,
			lights,
			darkness,
			globalLight,
			globalLightThreshold,
		} = generated;

		const imageRef = `${this.modulePrefix}/${spec.imageName}`;
		const body: string[] = [];
		body.push('\t{');
		body.push(`\t\tid: ${JSON.stringify(spec.sceneId)},`);
		body.push(`\t\tname: ${JSON.stringify(spec.sceneName)},`);
		body.push(`\t\timg: ${JSON.stringify(imageRef)},`);
		body.push('\t\tbackground: {');
		body.push(`\t\t\tsrc: ${JSON.stringify(imageRef)},`);
		body.push('\t\t},');
		body.push('\t\tgrid: {');
		body.push('\t\t\ttype: 1,');
		body.push(`\t\t\tsize: ${gridSize},`);
		body.push(`\t\t\tdistance: ${this.sceneDefaults.gridDistance},`);
		body.push("\t\t\tunits: 'ft',");
		body.push('\t\t},');
		body.push('\t\tinitial: {');
		body.push('\t\t\tx: null,');
		body.push('\t\t\ty: null,');
		body.push('\t\t\tscale: 1,');
		body.push('\t\t},');
		body.push(`\t\twidth: ${width},`);
		body.push(`\t\theight: ${height},`);
		body.push('\t\tnavigation: true,');
		body.push(`\t\tnavOrder: ${spec.navOrder},`);
		body.push(`\t\tfolder: ${JSON.stringify(spec.folder ?? this.sceneDefaults.defaultFolder)},`);
		body.push(`\t\tsort: ${spec.sort ?? this.sceneDefaults.defaultSort},`);
		if (darkness > 0) body.push(`\t\tdarkness: ${darkness},`);
		body.push(`\t\tglobalLight: ${globalLight},`);
		if (globalLightThreshold != null) {
			body.push(`\t\tglobalLightThreshold: ${globalLightThreshold},`);
		}
		if (spec.environment) {
			const environment = JSON.stringify(spec.environment, null, '\t').replace(/\n/g, '\n\t\t');
			body.push(`\t\tenvironment: ${environment},`);
		}
		body.push(`\t\twalls: ${JSON.stringify(walls, null, '\t').replace(/\n/g, '\n\t\t')},`);
		body.push(`\t\tlights: ${JSON.stringify(lights, null, '\t').replace(/\n/g, '\n\t\t')},`);
		body.push('\t},');
		return body.join('\n');
	}
}
