// =============================================================================
// WEAPON RUNES
// =============================================================================

export const WEAPON_RUNES = [
  'ancestral echoing',
  'anchoring',
  'anchoring (greater)',
  'animated',
  'ashen',
  'ashen (greater)',
  'astral',
  'astral (greater)',
  'authorized',
  'bane',
  'bloodbane',
  'bloodbane (greater)',
  'bloodthirsty',
  'brilliant',
  'brilliant (greater)',
  'called (weapon rune)',
  'coating',
  'conducting',
  'corrosive',
  'corrosive (greater)',
  'crushing',
  'crushing (greater)',
  'cunning',
  'deathdrinking',
  'decaying',
  'decaying (greater)',
  'demolishing',
  'earthbinding',
  'energizing',
  'extending',
  'extending (greater)',
  'fanged',
  'fanged (greater)',
  'fanged (major)',
  'fearsome',
  'fearsome (greater)',
  'flaming',
  'flaming (greater)',
  'flickering',
  'flurrying',
  'frost',
  'frost (greater)',
  'ghost touch',
  'giant-killing',
  'giant-killing (greater)',
  'grievous',
  'hauling',
  'hauling (greater)',
  'holy',
  'hooked',
  'hopeful',
  'impactful',
  'impactful (greater)',
  'impossible',
  'keen',
  'kin-warding',
  'merciful',
  'nightmare',
  'pacifying',
  'quickstrike',
  'returning',
  'rooting',
  'rooting (greater)',
  'rooting (major)',
  'rooting (true)',
  'serrating',
  'shifting',
  'shock',
  'shock (greater)',
  'shockwave',
  'spell reservoir',
  'swarming',
  'thundering',
  'thundering (greater)',
  'underwater',
  'unholy',
  'vitalizing',
  'vitalizing (greater)',
  'vorpal',
  'wounding'
] as const;

export type WeaponRune = typeof WEAPON_RUNES[number]
