// =============================================================================
// WEAPON RUNES
// =============================================================================

export const WEAPON_RUNES = [
  'ancestral echoing',
  'anchoring',
  'greaterAnchoring',
  'animated',
  'ashen',
  'greaterAshen',
  'astral',
  'greaterAstral',
  'authorized',
  'bane',
  'bloodbane',
  'greaterBloodbane',
  'bloodthirsty',
  'brilliant',
  'greaterBrilliant',
  'called (weapon rune)',
  'coating',
  'conducting',
  'corrosive',
  'greaterCorrosive',
  'crushing',
  'greaterCrushing',
  'cunning',
  'deathdrinking',
  'decaying',
  'greaterDecaying',
  'demolishing',
  'earthbinding',
  'energizing',
  'extending',
  'greaterExtending',
  'fanged',
  'greaterFanged',
  'majorFanged',
  'fearsome',
  'greaterFearsome',
  'flaming',
  'greaterFlaming',
  'flickering',
  'flurrying',
  'frost',
  'greaterFrost',
  'ghost touch',
  'giant-killing',
  'greaterGiantKilling',
  'grievous',
  'hauling',
  'greaterHauling',
  'holy',
  'hooked',
  'hopeful',
  'impactful',
  'greaterImpactful',
  'impossible',
  'keen',
  'kin-warding',
  'merciful',
  'nightmare',
  'pacifying',
  'quickstrike',
  'returning',
  'rooting',
  'greaterRooting',
  'majorRooting',
  'trueRooting',
  'serrating',
  'shifting',
  'shock',
  'greaterShock',
  'shockwave',
  'spell reservoir',
  'swarming',
  'thundering',
  'greaterThundering',
  'underwater',
  'unholy',
  'vitalizing',
  'greaterVitalizing',
  'vorpal',
  'wounding'
] as const;

export type WeaponRune = typeof WEAPON_RUNES[number]
