import fs from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import { ScenesModuleEmitter } from '../../../scripts/dd2vtt-importer/scenes-module-emitter';
import type { GeneratedScene, SceneDefaults } from '../../../scripts/dd2vtt-importer/types';
import { createTempDir } from '../helpers/dd2vtt-fixtures';

const sceneDefaults: SceneDefaults = {
	gridDistance: 5,
	defaultFolder: 'Chapter 1',
	defaultSort: 0,
	defaultGlobalLight: true,
	defaultGlobalLightThreshold: 0.749,
};

function buildGeneratedScene(overrides: Partial<GeneratedScene> = {}): GeneratedScene {
	const base: GeneratedScene = {
		spec: {
			input: '/tmp/scene.dd2vtt',
			imageName: 'Scene.png',
			sceneId: 'scene-test',
			sceneName: 'Scene Test',
			navOrder: 3,
			folder: 'Chapter 2',
			sort: 120,
			darkness: 0,
			globalLight: true,
			globalLightThreshold: 0.749,
		},
		width: 1200,
		height: 800,
		gridSize: 100,
		walls: [
			{
				light: 20,
				sight: 20,
				sound: 20,
				move: 20,
				c: [0, 0, 100, 0],
				dir: 0,
				door: 0,
				ds: 0,
				threshold: {
					light: null,
					sight: null,
					sound: null,
					attenuation: false,
				},
				animation: null,
				flags: {},
			},
		],
		lights: [],
		darkness: 0,
		globalLight: true,
		globalLightThreshold: 0.749,
	};
	return { ...base, ...overrides, spec: { ...base.spec, ...(overrides.spec ?? {}) } };
}

describe('ScenesModuleEmitter', () => {
	it('renders a deterministic TypeScript module with imported scenes', () => {
		const emitter = new ScenesModuleEmitter('modules/test-module/dist/assets/maps', sceneDefaults);
		const source = emitter.renderModule([
			buildGeneratedScene(),
			buildGeneratedScene({
				spec: {
					input: '/tmp/scene-night.dd2vtt',
					imageName: 'Scene Night.png',
					sceneId: 'scene-night',
					sceneName: 'Scene Night',
					navOrder: 4,
				},
				darkness: 0.6,
				globalLight: false,
			}),
		]);

		expect(source).toContain('AUTO-GENERATED by scripts/import-dd2vtt.ts');
		expect(source).toContain("export const IMPORTED_DD2VTT_SCENES: HarbingerScene[] = [");
		expect(source).toContain('id: "scene-test"');
		expect(source).toContain('img: "modules/test-module/dist/assets/maps/Scene.png"');
		expect(source).toContain('id: "scene-night"');
		expect(source).toContain('darkness: 0.6');
		expect(source).toContain('globalLight: false');
	});

	it('writes rendered content to disk', () => {
		const tempDir = createTempDir();
		const outputPath = path.join(tempDir, 'scenes-imported.ts');
		const emitter = new ScenesModuleEmitter('modules/test-module/dist/assets/maps', sceneDefaults);
		const source = emitter.renderModule([buildGeneratedScene()]);

		emitter.writeModule(outputPath, source);
		const written = fs.readFileSync(outputPath, 'utf8');

		expect(written).toBe(source);
	});
});
