/**
 * AUTO-GENERATED by scripts/import-dd2vtt.ts
 *
 * Scenes imported from Dungeondraft Universal VTT (.dd2vtt) exports.
 * Edit the source .dd2vtt files and re-run the importer instead of
 * hand-editing this file.
 */

import type { HarbingerScene } from './types';

export const IMPORTED_DD2VTT_SCENES: HarbingerScene[] = [
	{
		id: "scene-rooftop-chase-day",
		name: "Rooftop Chase (Day)",
		img: "modules/harbinger-house-pf2e/dist/assets/maps/Rooftop Chase - Day.png",
		background: {
			src: "modules/harbinger-house-pf2e/dist/assets/maps/Rooftop Chase - Day.png",
		},
		grid: {
			type: 1,
			size: 100,
			distance: 5,
			units: 'ft',
		},
		initial: {
			x: null,
			y: null,
			scale: 1,
		},
		width: 12000,
		height: 3000,
		navigation: true,
		navOrder: 10,
		folder: "Chapter 1",
		sort: 300,
		globalLight: true,
		globalLightThreshold: 0.749,
		walls: [
			{
				"light": 20,
				"sight": 20,
				"sound": 20,
				"move": 20,
				"c": [
					800,
					1950,
					850,
					1950
				],
				"dir": 0,
				"door": 0,
				"ds": 0,
				"threshold": {
					"light": null,
					"sight": null,
					"sound": null,
					"attenuation": false
				},
				"animation": null,
				"flags": {}
			},
			{
				"light": 20,
				"sight": 20,
				"sound": 20,
				"move": 20,
				"c": [
					950,
					1950,
					1050,
					1950
				],
				"dir": 0,
				"door": 0,
				"ds": 0,
				"threshold": {
					"light": null,
					"sight": null,
					"sound": null,
					"attenuation": false
				},
				"animation": null,
				"flags": {}
			},
			{
				"light": 20,
				"sight": 20,
				"sound": 20,
				"move": 20,
				"c": [
					5650,
					1000,
					6000,
					1000
				],
				"dir": 0,
				"door": 0,
				"ds": 0,
				"threshold": {
					"light": null,
					"sight": null,
					"sound": null,
					"attenuation": false
				},
				"animation": null,
				"flags": {}
			},
			{
				"light": 20,
				"sight": 20,
				"sound": 20,
				"move": 20,
				"c": [
					6100,
					1000,
					6400,
					1000
				],
				"dir": 0,
				"door": 0,
				"ds": 0,
				"threshold": {
					"light": null,
					"sight": null,
					"sound": null,
					"attenuation": false
				},
				"animation": null,
				"flags": {}
			},
			{
				"light": 20,
				"sight": 20,
				"sound": 20,
				"move": 20,
				"c": [
					850,
					1950,
					950,
					1950
				],
				"dir": 0,
				"door": 1,
				"ds": 0,
				"threshold": {
					"light": null,
					"sight": null,
					"sound": null,
					"attenuation": false
				},
				"animation": {
					"type": "swing",
					"texture": null,
					"flip": false,
					"double": false,
					"direction": 1,
					"duration": 750,
					"strength": 1
				},
				"flags": {},
				"doorSound": ""
			},
			{
				"light": 20,
				"sight": 20,
				"sound": 20,
				"move": 20,
				"c": [
					6000,
					1000,
					6100,
					1000
				],
				"dir": 0,
				"door": 1,
				"ds": 0,
				"threshold": {
					"light": null,
					"sight": null,
					"sound": null,
					"attenuation": false
				},
				"animation": {
					"type": "swing",
					"texture": null,
					"flip": false,
					"double": false,
					"direction": 1,
					"duration": 750,
					"strength": 1
				},
				"flags": {},
				"doorSound": ""
			}
		],
		lights: [],
	},
	{
		id: "scene-rooftop-chase-night",
		name: "Rooftop Chase (Night)",
		img: "modules/harbinger-house-pf2e/dist/assets/maps/Rooftop Chase - Night.png",
		background: {
			src: "modules/harbinger-house-pf2e/dist/assets/maps/Rooftop Chase - Night.png",
		},
		grid: {
			type: 1,
			size: 100,
			distance: 5,
			units: 'ft',
		},
		initial: {
			x: null,
			y: null,
			scale: 1,
		},
		width: 12000,
		height: 3000,
		navigation: true,
		navOrder: 11,
		folder: "Chapter 1",
		sort: 310,
		darkness: 0.6,
		globalLight: true,
		globalLightThreshold: 0.749,
		environment: {
			"cycle": true,
			"dark": {
				"hue": 0.7138888888888889,
				"luminosity": -0.25
			}
		},
		walls: [
			{
				"light": 20,
				"sight": 20,
				"sound": 20,
				"move": 20,
				"c": [
					800,
					1950,
					850,
					1950
				],
				"dir": 0,
				"door": 0,
				"ds": 0,
				"threshold": {
					"light": null,
					"sight": null,
					"sound": null,
					"attenuation": false
				},
				"animation": null,
				"flags": {}
			},
			{
				"light": 20,
				"sight": 20,
				"sound": 20,
				"move": 20,
				"c": [
					950,
					1950,
					1050,
					1950
				],
				"dir": 0,
				"door": 0,
				"ds": 0,
				"threshold": {
					"light": null,
					"sight": null,
					"sound": null,
					"attenuation": false
				},
				"animation": null,
				"flags": {}
			},
			{
				"light": 20,
				"sight": 20,
				"sound": 20,
				"move": 20,
				"c": [
					5650,
					1000,
					6000,
					1000
				],
				"dir": 0,
				"door": 0,
				"ds": 0,
				"threshold": {
					"light": null,
					"sight": null,
					"sound": null,
					"attenuation": false
				},
				"animation": null,
				"flags": {}
			},
			{
				"light": 20,
				"sight": 20,
				"sound": 20,
				"move": 20,
				"c": [
					6100,
					1000,
					6400,
					1000
				],
				"dir": 0,
				"door": 0,
				"ds": 0,
				"threshold": {
					"light": null,
					"sight": null,
					"sound": null,
					"attenuation": false
				},
				"animation": null,
				"flags": {}
			},
			{
				"light": 20,
				"sight": 20,
				"sound": 20,
				"move": 20,
				"c": [
					850,
					1950,
					950,
					1950
				],
				"dir": 0,
				"door": 1,
				"ds": 0,
				"threshold": {
					"light": null,
					"sight": null,
					"sound": null,
					"attenuation": false
				},
				"animation": {
					"type": "swing",
					"texture": null,
					"flip": false,
					"double": false,
					"direction": 1,
					"duration": 750,
					"strength": 1
				},
				"flags": {},
				"doorSound": ""
			},
			{
				"light": 20,
				"sight": 20,
				"sound": 20,
				"move": 20,
				"c": [
					6000,
					1000,
					6100,
					1000
				],
				"dir": 0,
				"door": 1,
				"ds": 0,
				"threshold": {
					"light": null,
					"sight": null,
					"sound": null,
					"attenuation": false
				},
				"animation": {
					"type": "swing",
					"texture": null,
					"flip": false,
					"double": false,
					"direction": 1,
					"duration": 750,
					"strength": 1
				},
				"flags": {},
				"doorSound": ""
			}
		],
		lights: [
			{
				"x": 978,
				"y": 1243,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 1765,
				"y": 1449,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 2233,
				"y": 1570,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 3299,
				"y": 2119,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 3164,
				"y": 930,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 4148,
				"y": 1770,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 4840,
				"y": 1664,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 4543,
				"y": 835,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 6195,
				"y": 549,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 6357,
				"y": 546,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 6152,
				"y": 894,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 5963,
				"y": 954,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 5984,
				"y": 1023,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 6129,
				"y": 1029,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 6193,
				"y": 1985,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 7892,
				"y": 1949,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 8854,
				"y": 1551,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 9028,
				"y": 558,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 9033,
				"y": 421,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 9339,
				"y": 533,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 9259,
				"y": 1990,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 9143,
				"y": 2980,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 10544,
				"y": 1539,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 10992,
				"y": 703,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			},
			{
				"x": 11707,
				"y": 1588,
				"rotation": 0,
				"walls": true,
				"vision": false,
				"elevation": 0,
				"config": {
					"negative": false,
					"priority": 0,
					"alpha": 0.04000000000000001,
					"angle": 360,
					"bright": 12.5,
					"color": "#eccd8b",
					"coloration": 1,
					"dim": 25,
					"attenuation": 0.5,
					"luminosity": 0.5,
					"saturation": 0,
					"contrast": 0,
					"shadows": 1,
					"darkness": {
						"min": 0,
						"max": 1
					},
					"animation": {
						"type": null,
						"speed": 5,
						"intensity": 5,
						"reverse": false
					}
				},
				"hidden": false,
				"flags": {}
			}
		],
	},
];
